// Generated by https://quicktype.io

// JSON data datatypes

export interface Image {
    filename: string;
}

export interface Photos{
    photos: Photo[];
}

export interface Photo {
    id?:       string;
    title?:    string;
    caption?:  string;
    source?:   string;
    comments?: Comment[];
}

export interface Comment {
    comment?: string;
    author?:  string;
}

//Props for Content
export interface ContentProps{
    selectedContent: number,
    collections: Photo[]
}

//Props for Jump
export interface JumpProps{    
    selectedContent: number;
    collections: Photo[],
    setSelectedContent: Function,
    enablePrev: boolean,
    setEnablePrev: Function,
    enableNext: boolean,
    setEnableNext: Function,
    toggleComment: boolean,
    setToggleComment: Function,
    showGallery: boolean,
    setShowGallery: Function
}

//Props for Comment
export interface CommentProps{
    selectedContent: number;
    collections: Photo[],
    setCollections: Function,
    toggleComment: boolean,
    setToggleComment: Function,
    setLoading: Function
}

//Props for Comment
export interface GalleryProps{
    showGallery: boolean,
    setSelectedContent: Function;
    collections: Photo[]
}

// export class ViewProps{
//     constructor(obj?: Partial<ViewProps>) {
//         Object.assign(this, obj);
//     }
//     selectedContent!: number | 0;
//     collections !: Photo[];
//     setSelectedContent !: Function;
//     enablePrev !: boolean;
//     setEnablePrev !: Function;
//     enableNext !: boolean;
//     setEnableNext !: Function;
//     toggleComment !: boolean;
//     setToggleComment !: Function;
//     showGallery !: boolean;
//     setShowGallery !: Function;
// }
